### PR TITLE
Allow outbound SMTP on the NAT

### PR DESCRIPTION
**Pull request by limed**

### CODE REVIEW

**Comment by limed** [comment]
Fixes issue #95

**Comment by tinnightcap** [comment]
I am not sure about this. I think we need to have a discussion about how to implement email forwarding with logging but doubt that infosec will be happy with just opening this up.

Is this blocking some work today? If we go this route it will at least need to be temporary with an issue opened to resolve it in the future. I would rather leave this closed for now, unless the answer to my question is yes.

**Comment by limed** [comment]
Actually it doesn't block anything, I was fixing another issue that I filed on this repo and thought that I just fix this as well (Call it a drive by fix if you may). So if further discussions need to be had I'm happy to just go ahead and close this PR

**Comment by gozer** [comment]
And adding to that conversation, if this ends up being something we can do, I'd like to make sure we don't limit it to tcp/25 but to also include tcp/465 and tcp/587

**Pull request closed without merging**
